var str_json = '{"status": "OK","usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html","url": "http://dfvbluemix.mybluemix.net/uploads/0I42Iq.jpg", "totalTransactions": "4","imageFaces": [{"age": {"ageRange": "18-24", "score": "0.355185"},"gender": {"gender": "MALE", "score": "0.995033"},"height": "78", "positionX": "289", "positionY": "256", "width": "78"}]}';
//console.log(str_json);
json_obj = JSON.parse(str_json);
console.log(json_obj.imageFaces[0].age.ageRange);
//console.log(json_obj.imageFaces[0].ageRange)